version: "3"
services:
  mongo:
    image: "mongo:latest"
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_PASSWORD=secret
      - MONGO_INITDB_ROOT_USERNAME=mongoadmin
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
  core-api:
    build: .docker/DockerfileCore
    env_file:
      - .env/.env.core.docker
    ports:
      - "8080:8080"
