name: build-profiles-api

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Build Profiles API
        run: go build -v ./profiles-api/...

      - name: Test Common
        run: go test -v ./common/...

      - name: Test Profiles API
        run: go test -v ./profiles-api/...

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./.docker/DockerfileProfilesApi
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/etheralley-profiles-api:${{ github.run_number }}
